/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Video;

import GUI_Generales.Editar;
import GUI_Generales.Instrucciones;
import GUI_Generales.Procesando;
import GUI_Generales.HiloProceso;
import static GUI_Video.PuntosVideo.vectorNodo;
import static GUI_Video.Video.rutaGeneral;
import herramientas.GestorVideo;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.application.Platform;
import javafx.beans.Observable;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.SwingConstants;
import org.bytedeco.javacpp.opencv_core;
import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.FrameGrabber;
import org.bytedeco.javacv.Java2DFrameConverter;
import org.bytedeco.javacv.OpenCVFrameConverter;

/**
 *
 * @author rebel
 */
public class CorreccionVideo extends javax.swing.JInternalFrame {

    public Procesando proceso;
    public JDesktopPane principal;
    public String rutaNueva;
    public List<BufferedImage> listaIm;
    public File file;
    public MediaPlayer oracleVid;
    public BufferedImage im,imagen;
    private final JFXPanel jfxPanel = new JFXPanel();
    public JButton boton;
    public int duracionV;
    public double fps;
    public String rutaEliminar;
    public String tipoProceso;
    public String nombreProc;
    public String nombreAlummno;
    public String grupo;
    public ImageIcon procesarP,menuP,playV,pauseV;
    /**
     * Creates new form CorreccionVideo
     */
    public CorreccionVideo() {
        initComponents();
    }

    CorreccionVideo(JDesktopPane principal, String rutaNueva,List<BufferedImage> listaIm, int duracionV,
            double fps, String tipoProceso) {
        
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        mostrarIconos();
        this.principal = principal;
        this.rutaNueva = rutaNueva;
        this.listaIm = listaIm;
        this.duracionV = duracionV;
        this.fps = fps;
        this.tipoProceso = tipoProceso;
        
//        muestraVideo();
        muestraVideo.setLayout(new BorderLayout());
        muestraVideo.add(jfxPanel, BorderLayout.CENTER);
        muestraVideo.repaint();
        Platform.setImplicitExit(false);
        this.setLocation((this.principal.getWidth()-this.getWidth())/2,(this.principal.getHeight()-this.getHeight())/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        procesar = new javax.swing.JButton();
        tiempo = new javax.swing.JButton();
        puntosInteres = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        muestraVideo = new javax.swing.JPanel();
        duracionVideo = new javax.swing.JSlider();
        play = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Panel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 4));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarActionPerformed(evt);
            }
        });

        tiempo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tiempo.setForeground(new java.awt.Color(0, 153, 153));
        tiempo.setText("Tiempo");
        tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoActionPerformed(evt);
            }
        });

        puntosInteres.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        puntosInteres.setForeground(new java.awt.Color(0, 153, 153));
        puntosInteres.setText("Puntos de interés");
        puntosInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntosInteresActionPerformed(evt);
            }
        });

        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(procesar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(tiempo)
                .addGap(16, 16, 16)
                .addComponent(puntosInteres)
                .addGap(20, 20, 20)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(procesar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiempo)
                    .addComponent(puntosInteres)
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        muestraVideo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout muestraVideoLayout = new javax.swing.GroupLayout(muestraVideo);
        muestraVideo.setLayout(muestraVideoLayout);
        muestraVideoLayout.setHorizontalGroup(
            muestraVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        muestraVideoLayout.setVerticalGroup(
            muestraVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        duracionVideo.setSnapToTicks(true);
        duracionVideo.setValue(0);

        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(duracionVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pause, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(muestraVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(muestraVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pause, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(duracionVideo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel.setLayout(new java.awt.GridLayout(1, 2));
        jScrollPane1.setViewportView(Panel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void puntosInteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntosInteresActionPerformed
        ///////////QUE SE BORRE TODO
        Editar.gc = false;
        Instrucciones.ac = false;
        PuntosVideo.vectorNodo.clear();
        CorreccionPuntosV cp = new CorreccionPuntosV(this.principal);
        this.principal.add(cp);
        cp.setVisible(true);
        
    }//GEN-LAST:event_puntosInteresActionPerformed

    private void procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarActionPerformed
        dispose();
        proceso = new Procesando(this.principal);
        this.principal.add(proceso);
        HiloProceso.active = true;
        HiloProceso h = new HiloProceso(proceso,this.listaIm,2);
        h.pasarProceso("",nombreAlummno,grupo,nombreProc);
        h.darProcesando(proceso);
        
        h.start();
    }//GEN-LAST:event_procesarActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        int max = duracionVideo.getMaximum() - 1;
        int act = duracionVideo.getValue();
       
        if(max == act){
            oracleVid.stop();
            duracionVideo.setValue(0);
        }
        oracleVid.play();
    }//GEN-LAST:event_playActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        oracleVid.pause();
    }//GEN-LAST:event_pauseActionPerformed

    private void tiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoActionPerformed
        dispose();
        //Eliminar carpeta con las cosas(Imagenes)
        SeleccionTiempo st = new SeleccionTiempo(this.principal,this.duracionV,this.rutaNueva,this.fps);
        st.agregarProyecto(nombreProc, nombreAlummno, grupo);
        this.principal.add(st);
        st.setVisible(true);
    }//GEN-LAST:event_tiempoActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        ////////////ELIMINAR TODO HASTA LA CARPETA CREADA
        GestorVideo.video = null;
        archivo();
        eliminarArchivo(rutaEliminar);
        eliminarArchivo(rutaGeneral);
        GUI_Video.PuntosVideo.forma = 0;
        Editar.gc = false;
        Instrucciones.ac = false;
        vectorNodo.clear();
        System.gc();
        dispose();
        GUI_Generales.Principal.archivos.setEnabled(true);
        GUI_Generales.Principal.creditos.setEnabled(true);
    }//GEN-LAST:event_menuActionPerformed

    public void archivo(){
        
        Calendar fecha = Calendar.getInstance();
        String fechaDia = fecha.get(Calendar.DAY_OF_MONTH)+"-"+fecha.get(Calendar.MONTH)+"-"+fecha.get(Calendar.YEAR);
        String rutaUsuario = System.getProperty("user.home");
        rutaEliminar = rutaUsuario+"\\Documents\\SMIM\\"+ 
                tipoProceso+"\\"+fechaDia+"_"+
                nombreProc+"_"+nombreAlummno+"_"+
                grupo;
    }
    
    public void eliminarArchivo(String ruta){
        File rutaG = new File(ruta);
        if(rutaG.isDirectory()){
            if(rutaG.list().length == 0){
                rutaG.delete();
            }else{
                for(String temp : rutaG.list()){
                    File file = new File(rutaG,temp);
                    eliminarArchivo(file.getAbsolutePath());
                }
                if(rutaG.list().length == 0){
                    rutaG.delete();
                }
            }
        }else{
            rutaG.delete();
        }       
    }
    
    public void muestraVideo(){
        try {
            file = new File(rutaNueva);
            oracleVid = new MediaPlayer(
                        new Media(file.toURI().toString())
            );
            //se añade video al jfxPanel
            im = obtenerImagen(rutaNueva);
            int w = im.getWidth();
            int h = im.getHeight();
            jfxPanel.setPreferredSize(new Dimension(w,h));
            jfxPanel.setScene(new Scene(new Group(new MediaView(oracleVid))));
            oracleVid.currentTimeProperty().addListener((Observable ov) -> {
                duracionVideo.setValue((int) (oracleVid.getCurrentTime().toMillis()/oracleVid.getTotalDuration().toMillis()* 100));
            });
        } catch (FrameGrabber.Exception ex) {
            Logger.getLogger(Video.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void muestraImagenes(){
        double op = (double)listaIm.size()/2;
        double rows = Math.ceil(op);
        Panel.setLayout(new GridLayout((int) rows,2));
        
        for(int i=0; i<listaIm.size(); i++){
            imagen = listaIm.get(i);
            boton = new JButton();
            boton.setContentAreaFilled(false);
            boton.setHorizontalTextPosition(SwingConstants.CENTER);
            boton.setVerticalTextPosition(SwingConstants.BOTTOM);
            int g = (Panel.getWidth())-((35*Panel.getWidth())/100);
            int g2 = (Panel.getWidth())-((26*Panel.getWidth())/100);
            boton.setRolloverIcon(new ImageIcon(imagen.getScaledInstance((int) (g2/1.5),
                    (int) (g2/1.5),Image.SCALE_DEFAULT)));
            boton.setIcon(new ImageIcon(imagen.getScaledInstance(g/2,
                    g/2,Image.SCALE_DEFAULT)));
            Panel.add(boton);
            Panel.updateUI();
        }
    }
    
    public BufferedImage obtenerImagen(String ruta) throws FrameGrabber.Exception{
        
        try {
            // ruta donde se selecciona el video para tomar los frames
            FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber(ruta);
            // se inicia preparativos para obtener frames
            frameGrabber.start();
            // objeto de tipo frame
            Frame i;
            //objeto del cual convertira el frame del video en imagen
            OpenCVFrameConverter.ToIplImage converterToIplImage = 
                    new OpenCVFrameConverter.ToIplImage();
            int j = 30; //frame numero 30 equivale a 1s
            
            // seleccionas que frame vas a querer, en este caso el frame de 1s en el video, que es el
            // numero 30.
            frameGrabber.setFrameNumber(j);//puede ser cualquier frame
            // se obtiene la imagen
            org.bytedeco.javacv.Frame frame = frameGrabber.grabImage();
            //muestras informacion de la imagen obtenida
//            System.out.println(frame.toString());
            // se inicia la conversion de frame a imagen
            opencv_core.IplImage image = converterToIplImage.convert(frame);
            // se crea un buffered con el frame obtenido
            BufferedImage bi = IplImageToBufferedImage(image);
            
            return bi;
        } catch (FrameGrabber.Exception ex) {
            Logger.getLogger(Video.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    private BufferedImage IplImageToBufferedImage( opencv_core.IplImage src ) {
        
        OpenCVFrameConverter.ToIplImage grabberConverter = 
                new OpenCVFrameConverter.ToIplImage();
        
        Java2DFrameConverter paintConverter = new Java2DFrameConverter();
        org.bytedeco.javacv.Frame frame = grabberConverter.convert( src );
        
        return paintConverter.getBufferedImage( frame,1 );
    }
    
    public void agregarProyecto(String nombreProc, String nombreAlummno , String grupo){
        this.nombreProc = nombreProc;
        this.nombreAlummno = nombreAlummno;
        this.grupo = grupo;
    }
    
    private void mostrarIconos() {
        procesarP = new ImageIcon("src\\Fotos\\play.png");
        menuP = new ImageIcon("src\\Fotos\\menu.png");
        playV = new ImageIcon("src\\Fotos\\play.png");
        pauseV = new ImageIcon("src\\Fotos\\pausa.png");
        
        procesarP.setImage(procesarP.getImage().getScaledInstance(30,30,Image.SCALE_DEFAULT));
        menuP.setImage(menuP.getImage().getScaledInstance(30,30,Image.SCALE_DEFAULT));
        playV.setImage(playV.getImage().getScaledInstance(30,30,Image.SCALE_DEFAULT));
        pauseV.setImage(pauseV.getImage().getScaledInstance(30,30,Image.SCALE_DEFAULT));
        
        procesar.setIcon(procesarP);
        menu.setIcon(menuP);
        play.setIcon(playV);
        pause.setIcon(pauseV);
        
        procesar.setContentAreaFilled(false);
        menu.setContentAreaFilled(false);
        play.setContentAreaFilled(false);
        pause.setContentAreaFilled(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JSlider duracionVideo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menu;
    private javax.swing.JPanel muestraVideo;
    private javax.swing.JButton pause;
    private javax.swing.JButton play;
    private javax.swing.JButton procesar;
    private javax.swing.JButton puntosInteres;
    private javax.swing.JButton tiempo;
    // End of variables declaration//GEN-END:variables

}
