/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Video;

import static GUI_Generales.Principal.Tiempo;
import static herramientas.GestorVideo.video;

import herramientas.GestorVideo;
import java.awt.image.BufferedImage;
import java.util.List;
import javax.swing.JDesktopPane;

/**
 *
 * @author rebel
 */
public class SeleccionTiempo extends javax.swing.JInternalFrame {

    public JDesktopPane principal;
    public List<BufferedImage> listaIm;
    public int duracionV;
    public String rutaNueva;
    public double fps;
    public String nombreProc;
    public String nombreAlummno;
    public String grupo;
    /**
     * Creates new form SeleccionTiempo
     */
    public SeleccionTiempo() {
        initComponents();
    }

    SeleccionTiempo(JDesktopPane principal, int duracionV, String rutaNueva,double fps) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.principal = principal;
        this.duracionV = duracionV;
        this.rutaNueva = rutaNueva;
        this.fps = fps;
        for(int y=0; y<Tiempo.size(); y++){
            tiempoImagenes.addItem(Tiempo.get(y));
        }
        this.setLocation((this.principal.getWidth()-this.getWidth())/2,(this.principal.getHeight()-this.getHeight())/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tiempoImagenes = new javax.swing.JComboBox<>();
        aceptar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 6));

        jLabel1.setText("Selección de segundos para la obtención de imágenes:");

        tiempoImagenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion" }));

        aceptar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        aceptar.setForeground(new java.awt.Color(0, 153, 153));
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(tiempoImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(aceptar)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tiempoImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(aceptar)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        listaIm = GestorVideo.obtenerRutaNueva(video,Integer.parseInt(Tiempo.get(tiempoImagenes.getSelectedIndex()-1)),duracionV,fps);
        int index = tiempoImagenes.getSelectedIndex();
        String tipo = tiempoImagenes.getItemAt(index);
        CorreccionVideo cv = new CorreccionVideo(this.principal,this.rutaNueva,listaIm,duracionV,this.fps,tipo);
        cv.agregarProyecto(nombreProc, nombreAlummno, grupo);
        this.principal.add(cv);
        cv.muestraImagenes();
        cv.muestraVideo();
        cv.setVisible(true);
        dispose();
    }//GEN-LAST:event_aceptarActionPerformed

    public void agregarProyecto(String nombreProc, String nombreAlummno , String grupo){
        this.nombreProc = nombreProc;
        this.nombreAlummno = nombreAlummno;
        this.grupo = grupo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> tiempoImagenes;
    // End of variables declaration//GEN-END:variables
}
