/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Imagenes;

import GUI_Generales.HiloProceso;
import GUI_Generales.Procesando;
import static herramientas.GestorImagenes.rutas;


import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.SwingConstants;
import javax.swing.Timer;

/**
 *
 * @author rebel
 */
public class CorreccionImagenes extends javax.swing.JInternalFrame {
    
    public JButton boton;
    public JDesktopPane principal;
    public int s;
    public ImageIcon imagen[] ;
    public int contador = 1;
    public Timer timer;
    public List<BufferedImage> listaIm;
    public String nProceso;
    public String nombre;
    public String grupo;
    public String nombreProceso;
    public Procesando proceso;
    public int forma;
    public ImageIcon playI,pauseI,atras,adelante,procesarF,menuS;
    /**
     * Creates new form CorrecciónImagenes
     */
    public CorreccionImagenes() {
        initComponents();
        this.setLocation((this.principal.getWidth()-this.getWidth())/2,(this.principal.getHeight()-this.getHeight())/2);
    }

    CorreccionImagenes(JDesktopPane principal, List<BufferedImage> listaIm) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        ponerIconos();
        this.listaIm = listaIm;
        s = listaIm.size();
        imagen = new ImageIcon[s];
        
        this.principal = principal;
        this.setLocation((this.principal.getWidth()-this.getWidth())/2,(this.principal.getHeight()-this.getHeight())/2);
        for(int i=1; i<listaIm.size(); i++){
            imagen[i] = new ImageIcon(rutas.get(i));
        }
        mostrarImagenes.setIcon(new ImageIcon(imagen[1].getImage().getScaledInstance(440,
                440,Image.SCALE_DEFAULT)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        procesar = new javax.swing.JButton();
        seleccionarPuntos = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        mostrarImagenes = new javax.swing.JLabel();
        play = new javax.swing.JButton();
        izquierda = new javax.swing.JButton();
        derecha = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Panel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 4));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        procesar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarActionPerformed(evt);
            }
        });

        seleccionarPuntos.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        seleccionarPuntos.setForeground(new java.awt.Color(0, 153, 153));
        seleccionarPuntos.setText("Seleccionar Puntos");
        seleccionarPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarPuntosActionPerformed(evt);
            }
        });

        menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(procesar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(seleccionarPuntos)
                .addGap(54, 54, 54)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(procesar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionarPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        mostrarImagenes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        izquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izquierdaActionPerformed(evt);
            }
        });

        derecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derechaActionPerformed(evt);
            }
        });

        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mostrarImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(pause, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mostrarImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pause, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Panel.setLayout(new java.awt.GridLayout(1, 2));
        jScrollPane1.setViewportView(Panel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 625, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        timer = new Timer(600,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                mostrarImagenes.setIcon(new ImageIcon(new javax.swing.ImageIcon(rutas.get(contador)).
                        getImage().getScaledInstance(440,440,Image.SCALE_DEFAULT)));
                contador++;
                if(contador == s){
                    contador = 1;
                }
            }
        });
        timer.start();
    }//GEN-LAST:event_playActionPerformed

    private void izquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izquierdaActionPerformed
        if(contador == 1){
            contador =s;
        }
        contador--;
        mostrarImagenes.setIcon(new ImageIcon(imagen[contador].getImage().getScaledInstance(440,
                440,Image.SCALE_DEFAULT)));
//        mostrarImagenes.setIcon(imagen[contador]);
    }//GEN-LAST:event_izquierdaActionPerformed

    private void derechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derechaActionPerformed
        if(contador == s-1){
            contador = 0;
        }
        contador++;
        mostrarImagenes.setIcon(new ImageIcon(imagen[contador].getImage().getScaledInstance(440,
                440,Image.SCALE_DEFAULT)));
//        mostrarImagenes.setIcon(imagen[contador]);
    }//GEN-LAST:event_derechaActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        if(timer.isRunning()){
            timer.stop();
        }
    }//GEN-LAST:event_pauseActionPerformed

    private void seleccionarPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarPuntosActionPerformed
        CorreccionPuntosI correccion = new CorreccionPuntosI(this.principal);
        this.principal.add(correccion);
        correccion.setVisible(true);
    }//GEN-LAST:event_seleccionarPuntosActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        Imagenes.vectorNodo.clear();
        rutas.clear();
        Imagenes.btn = null;
        dispose();
        GUI_Generales.Principal.archivos.setEnabled(true);
        GUI_Generales.Principal.creditos.setEnabled(true);
    }//GEN-LAST:event_menuActionPerformed

    private void procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarActionPerformed
        dispose();
        proceso = new Procesando(this.principal);
        this.principal.add(proceso);
        HiloProceso.active = true;
        HiloProceso h = new HiloProceso(proceso,this.listaIm,1);
        h.darProcesando(proceso);
        h.pasarProceso(this.nProceso,nombre,grupo,nombreProceso);
        h.forma(forma);
        h.start();
    }//GEN-LAST:event_procesarActionPerformed

    public void muestra(){
        Panel.setLayout(new GridLayout((int)(rutas.size()/2),2));
        BufferedImage leerImagen;
        File extension;
        
        for(int i=0; i<rutas.size(); i++){
            try {
                extension = new File(rutas.get(i));
                leerImagen = ImageIO.read(extension);
                boton = new JButton();
                
                boton.setContentAreaFilled(false);
                boton.setHorizontalTextPosition(SwingConstants.CENTER);
                boton.setVerticalTextPosition(SwingConstants.BOTTOM);
                int g = (Panel.getWidth())-((35*Panel.getWidth())/100);
                int g2 = (Panel.getWidth())-((26*Panel.getWidth())/100);
                boton.setRolloverIcon(new ImageIcon(leerImagen.getScaledInstance((int) (g2/1.5), 
                        (int) (g2/1.5),Image.SCALE_DEFAULT)));
                boton.setIcon(new ImageIcon(leerImagen.getScaledInstance(g/2,
                        g/2,Image.SCALE_DEFAULT)));
                Panel.add(boton);
                Panel.updateUI();
                
            } catch (IOException ex) {
                Logger.getLogger(CorreccionImagenes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public void pasarProceso(String nProceso, String nom, String g, String np) {
        this.nProceso = nProceso;
        this.nombre = nom;
        this.grupo = g;
        this.nombreProceso = np;
    }
    
    public void forma(int f) {
       forma = f;
    }
    
    private void ponerIconos() {
        playI = new ImageIcon("src\\Fotos\\play.png");
        pauseI = new ImageIcon("src\\Fotos\\pausa.png");
        atras = new ImageIcon("src\\Fotos\\atras.png");
        adelante = new ImageIcon("src\\Fotos\\adelante.png");
        procesarF = new ImageIcon("src\\Fotos\\play.png");
        menuS = new ImageIcon("src\\Fotos\\menu.png");
        
        playI.setImage(playI.getImage().getScaledInstance(30,30,Image.SCALE_DEFAULT));
        pauseI.setImage(pauseI.getImage().getScaledInstance(30,30,Image.SCALE_DEFAULT));
        atras.setImage(atras.getImage().getScaledInstance(50,30,Image.SCALE_DEFAULT));
        adelante.setImage(adelante.getImage().getScaledInstance(50,30,Image.SCALE_DEFAULT));
        procesarF.setImage(procesarF.getImage().getScaledInstance(30,30,Image.SCALE_DEFAULT));
        menuS.setImage(menuS.getImage().getScaledInstance(30,30,Image.SCALE_DEFAULT));
        
        play.setIcon(playI);
        pause.setIcon(pauseI);
        izquierda.setIcon(atras);
        derecha.setIcon(adelante);
        procesar.setIcon(procesarF);
        menu.setIcon(menuS);
        
        play.setContentAreaFilled(false);
        pause.setContentAreaFilled(false);
        izquierda.setContentAreaFilled(false);
        derecha.setContentAreaFilled(false);
        procesar.setContentAreaFilled(false);
        menu.setContentAreaFilled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton derecha;
    private javax.swing.JButton izquierda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menu;
    private javax.swing.JLabel mostrarImagenes;
    private javax.swing.JButton pause;
    private javax.swing.JButton play;
    private javax.swing.JButton procesar;
    private javax.swing.JButton seleccionarPuntos;
    // End of variables declaration//GEN-END:variables

    
}
