/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Imagenes;

import GUI_Generales.HiloProceso;
import GUI_Generales.Procesando;
import static herramientas.GestorImagenes.rutas;


import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.SwingConstants;
import javax.swing.Timer;

/**
 *
 * @author rebel
 */
public class CorreccionImagenes extends javax.swing.JInternalFrame {
    
    public JButton boton;
    public JDesktopPane principal;
    public int s;
//    public ImageIcon imagen[] = new ImageIcon[Imagenes.listaIm.size()];
    public ImageIcon imagen[] ;
    public int contador = 1;
    public Timer timer;
    public List<BufferedImage> listaIm;
    public String nProceso;
    public String nombre;
    public String grupo;
    public String nombreProceso;
    public Procesando proceso;
    /**
     * Creates new form CorrecciónImagenes
     */
    public CorreccionImagenes() {
        initComponents();
        this.setLocation((this.principal.getWidth()-this.getWidth())/2,(this.principal.getHeight()-this.getHeight())/2);
    }

//    CorreccionImagenes(JDesktopPane principal) {
//        initComponents();
//        this.principal = principal;
//        this.setLocation((this.principal.getWidth()-this.getWidth())/2,(this.principal.getHeight()-this.getHeight())/2);
//        for(int i=1; i<Imagenes.listaIm.size(); i++){
//            imagen[i] = new ImageIcon(rutas.get(i));
//        }
//        mostrarImagenes.setIcon(new ImageIcon(imagen[1].getImage().getScaledInstance(440,
//                440,Image.SCALE_DEFAULT)));
//    }

    CorreccionImagenes(JDesktopPane principal, List<BufferedImage> listaIm) {
        initComponents();
        this.listaIm = listaIm;
        s = listaIm.size();
        ImageIcon imagen[] = new ImageIcon[s];
        
        this.principal = principal;
        this.setLocation((this.principal.getWidth()-this.getWidth())/2,(this.principal.getHeight()-this.getHeight())/2);
        for(int i=1; i<listaIm.size(); i++){
            imagen[i] = new ImageIcon(rutas.get(i));
        }
        mostrarImagenes.setIcon(new ImageIcon(imagen[1].getImage().getScaledInstance(440,
                440,Image.SCALE_DEFAULT)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        procesar = new javax.swing.JButton();
        seleccionarPuntos = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        mostrarImagenes = new javax.swing.JLabel();
        play = new javax.swing.JButton();
        izquierda = new javax.swing.JButton();
        derecha = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Panel = new javax.swing.JPanel();

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        procesar.setText("Procesar");
        procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarActionPerformed(evt);
            }
        });

        seleccionarPuntos.setText("Seleccionar Puntos");
        seleccionarPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarPuntosActionPerformed(evt);
            }
        });

        menu.setText("Menú");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(procesar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seleccionarPuntos)
                .addGap(40, 40, 40)
                .addComponent(menu)
                .addGap(35, 35, 35))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(procesar)
                    .addComponent(seleccionarPuntos)
                    .addComponent(menu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mostrarImagenes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        play.setText("Play");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        izquierda.setText("<<");
        izquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izquierdaActionPerformed(evt);
            }
        });

        derecha.setText(">>");
        derecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derechaActionPerformed(evt);
            }
        });

        pause.setText("Pause");
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mostrarImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(izquierda)
                        .addGap(35, 35, 35)
                        .addComponent(play)
                        .addGap(38, 38, 38)
                        .addComponent(pause)
                        .addGap(43, 43, 43)
                        .addComponent(derecha)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mostrarImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(play)
                    .addComponent(izquierda)
                    .addComponent(derecha)
                    .addComponent(pause))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Panel.setLayout(new java.awt.GridLayout(1, 2));
        jScrollPane1.setViewportView(Panel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        timer = new Timer(600,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                mostrarImagenes.setIcon(new ImageIcon(new javax.swing.ImageIcon(rutas.get(contador)).
                        getImage().getScaledInstance(440,440,Image.SCALE_DEFAULT)));
                contador++;
                if(contador == s){
                    contador = 1;
                }
            }
        });
        timer.start();
    }//GEN-LAST:event_playActionPerformed

    private void izquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izquierdaActionPerformed
        if(contador == 1){
            contador =s;
        }
        contador--;
        mostrarImagenes.setIcon(new ImageIcon(imagen[contador].getImage().getScaledInstance(440,
                440,Image.SCALE_DEFAULT)));
//        mostrarImagenes.setIcon(imagen[contador]);
    }//GEN-LAST:event_izquierdaActionPerformed

    private void derechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derechaActionPerformed
        if(contador == s-1){
            contador = 0;
        }
        contador++;
        mostrarImagenes.setIcon(new ImageIcon(imagen[contador].getImage().getScaledInstance(440,
                440,Image.SCALE_DEFAULT)));
//        mostrarImagenes.setIcon(imagen[contador]);
    }//GEN-LAST:event_derechaActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        timer.stop();
    }//GEN-LAST:event_pauseActionPerformed

    private void seleccionarPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarPuntosActionPerformed
        CorreccionPuntosI correccion = new CorreccionPuntosI(this.principal);
        this.principal.add(correccion);
        correccion.setVisible(true);
    }//GEN-LAST:event_seleccionarPuntosActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        Imagenes.vectorNodo.clear();
        rutas.clear();
        Imagenes.btn = null;
        dispose();
    }//GEN-LAST:event_menuActionPerformed

    private void procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarActionPerformed
        dispose();
        proceso = new Procesando(this.principal);
        this.principal.add(proceso);
        HiloProceso.active = true;
        HiloProceso h = new HiloProceso(proceso,this.listaIm,1);
        h.darProcesando(proceso);
        h.pasarProceso(this.nProceso,nombre,grupo,nombreProceso);
        
        h.start();
    }//GEN-LAST:event_procesarActionPerformed

    public void muestra(){
        Panel.setLayout(new GridLayout((int)(rutas.size()/2),2));
        BufferedImage leerImagen;
        File extension;
        
        for(int i=0; i<rutas.size(); i++){
            try {
                extension = new File(rutas.get(i));
                leerImagen = ImageIO.read(extension);
                boton = new JButton();
                
                boton.setContentAreaFilled(false);
                boton.setHorizontalTextPosition(SwingConstants.CENTER);
                boton.setVerticalTextPosition(SwingConstants.BOTTOM);
                int g = (Panel.getWidth())-((35*Panel.getWidth())/100);
                int g2 = (Panel.getWidth())-((26*Panel.getWidth())/100);
                boton.setRolloverIcon(new ImageIcon(leerImagen.getScaledInstance((int) (g2/1.5), 
                        (int) (g2/1.5),Image.SCALE_DEFAULT)));
                boton.setIcon(new ImageIcon(leerImagen.getScaledInstance(g/2,
                        g/2,Image.SCALE_DEFAULT)));
                Panel.add(boton);
                Panel.updateUI();
                
            } catch (IOException ex) {
                Logger.getLogger(CorreccionImagenes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public void pasarProceso(String nProceso, String nom, String g, String np) {
        this.nProceso = nProceso;
        this.nombre = nom;
        this.grupo = g;
        this.nombreProceso = np;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton derecha;
    private javax.swing.JButton izquierda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menu;
    private javax.swing.JLabel mostrarImagenes;
    private javax.swing.JButton pause;
    private javax.swing.JButton play;
    private javax.swing.JButton procesar;
    private javax.swing.JButton seleccionarPuntos;
    // End of variables declaration//GEN-END:variables

}
