/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Generales;

import java.awt.Color;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author Alejandra
 */
public class Inicio extends javax.swing.JFrame implements Runnable{

    public ImageIcon icono,logoIpn,logoUpiiz;
    public Thread hiloCargando;
    public int contador;
    /**
     * Creates new form Principal
     */
    public Inicio() {
        initComponents();
        muestraFondo();
        
        color();
        
        this.setLocationRelativeTo(null);
        
        hiloCargando=new Thread(this);
        hiloCargando.start();
    }
    
    public final void muestraFondo(){
        icono = new ImageIcon("src\\Fotos\\Inicio.jpg");
        logoIpn = new ImageIcon("src\\Fotos\\ipn.png");
        logoUpiiz = new ImageIcon("src\\Fotos\\upiiz.png");
        icono.setImage(icono.getImage().getScaledInstance(this.getWidth(),this.getHeight(),Image.SCALE_DEFAULT));
        logoIpn.setImage(logoIpn.getImage().getScaledInstance(90,80,Image.SCALE_DEFAULT));
        logoUpiiz.setImage(logoUpiiz.getImage().getScaledInstance(60,60,Image.SCALE_DEFAULT));
        fondo.setIcon(icono);
        ipn.setIcon(logoIpn);
        upiiz.setIcon(logoUpiiz);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loading = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ipn = new javax.swing.JLabel();
        upiiz = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(500, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loading.setBackground(new java.awt.Color(102, 102, 102));
        loading.setForeground(new java.awt.Color(102, 102, 102));
        loading.setValue(10);
        loading.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        loading.setRequestFocusEnabled(false);
        loading.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 610, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Desarrollado Por: Isaul Ibarra, Alejandra Beltran");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Unidad Profesional Interdisciplinaria");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 490, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("De Ingeniería Campus Zacatecas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 440, -1));
        getContentPane().add(ipn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 100));
        getContentPane().add(upiiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 70, 70));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("V 1.0");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 26)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Instituto Politécnico Nacional");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 410, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Sistema de Medición");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 330, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Infrarroja y Maquinado");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 370, -1));

        fondo.setForeground(new java.awt.Color(103, 163, 133));
        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel ipn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar loading;
    private javax.swing.JLabel upiiz;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        loading.setStringPainted(true);
        try{
            for(contador = 0; contador<=100; contador++){
                Thread.sleep(100);
                loading.setString(contador+"%");
                loading.setValue(contador);
                if( contador==100 ){
                    Principal p = new Principal();
                    p.setVisible(true);
                    hiloCargando.interrupt();
                }
            }
        }catch(InterruptedException ex){
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
//        int i = 0;
//        loading.setStringPainted(true);
//        
//        while(true){
//            try {
//                this.loading.setValue(i);
//                
//                loading.setString(i+"%");
//                
//                if(i == 100){
//                    i = -1;
//                }
//                
//                i++;
//                Thread.sleep(300);
//            } catch (InterruptedException ex) {
//                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
//        int i = 0;
//        loading.setStringPainted(true);
//        
//        while(true){
//            try {
//                this.loading.setValue(i);
//                
//                loading.setString(i+"%");
//                
//                if(i == 100){
//                    i = -1;
//                }
//                
//                i++;
//                Thread.sleep(300);
//            } catch (InterruptedException ex) {
//                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
        
    }

    private void color() {
        UIManager.put( "nimbusOrange", new Color( 102,102,102 ) );
        loading.setBorderPainted(true);
        loading.setBorder(javax.swing.BorderFactory.createLineBorder(Color.GRAY));
    }
}
