/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Generales;


import static herramientas.GestorImagenes.rutas;
import static herramientas.GestorVideo.video;

import GUI_Imagenes.Pasos;
import GUI_Imagenes.Validacion;
import GUI_Video.Video;
import herramientas.GestorImagenes;
import herramientas.GestorVideo;
import it.sauronsoftware.jave.Encoder;
import it.sauronsoftware.jave.EncoderException;
import it.sauronsoftware.jave.MultimediaInfo;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandra
 */
public class Prueba extends javax.swing.JFrame {
    
    public static int maxPuntos = 4, maxImagenes = 30;
    public static int duracionVideo = 300;
    public static ArrayList<String> Procesos,Tiempo;
    
    public int respuestaSeguridad;
    public int x,y;
    public boolean abrirImagenes;
    public boolean abrirVideo;
    public Seguridad ventanaSeguridad;
    public Pasos pasos;
    public Cargando cargando;
    
    public int respuestaOk;
    /**
     * Creates new form Prueba
     */
    public Prueba() {
        initComponents();
//        this.setResizable(true);
        this.setSize(1200,800);
        this.setLocationRelativeTo(this);
        this.setTitle("SMIM");
        
        Procesos = new ArrayList<>();
        Procesos.add("Soldadura");
        Procesos.add("Fundicion");
        Procesos.add("Manufactura");
        
        Tiempo = new ArrayList<>();
        Tiempo.add("10");
        Tiempo.add("15");
//        this.setExtendedState(MAXIMIZED_BOTH);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JDesktopPane();
        barra = new javax.swing.JMenuBar();
        archivos = new javax.swing.JMenu();
        AbrirVideo = new javax.swing.JMenuItem();
        AbrirImagen = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        VerRegistro = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Salir = new javax.swing.JMenuItem();
        creditos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        barra.setBackground(new java.awt.Color(255, 0, 0));
        barra.setForeground(new java.awt.Color(255, 51, 51));
        barra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        archivos.setText("Archivos");

        AbrirVideo.setText("Abrir Video");
        AbrirVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirVideoActionPerformed(evt);
            }
        });
        archivos.add(AbrirVideo);

        AbrirImagen.setText("Abrir Imagen");
        AbrirImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirImagenActionPerformed(evt);
            }
        });
        archivos.add(AbrirImagen);
        archivos.add(jSeparator1);

        VerRegistro.setText("Registro");
        VerRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerRegistroActionPerformed(evt);
            }
        });
        archivos.add(VerRegistro);
        archivos.add(jSeparator2);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        archivos.add(Salir);

        barra.add(archivos);

        creditos.setText("Créditos");
        creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditosActionPerformed(evt);
            }
        });
        barra.add(creditos);

        setJMenuBar(barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void AbrirImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirImagenActionPerformed
        archivos.setEnabled(false);
        creditos.setEnabled(false);  
        abrirI();
    }//GEN-LAST:event_AbrirImagenActionPerformed

    private void AbrirVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirVideoActionPerformed
        archivos.setEnabled(false);
        creditos.setEnabled(false);
        abrirV();
    }//GEN-LAST:event_AbrirVideoActionPerformed

    private void VerRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerRegistroActionPerformed
//        Cargando c = new Cargando();
//        principal.add(c);
//        c.setVisible(true);
        archivos.setEnabled(false);
        creditos.setEnabled(false);
    }//GEN-LAST:event_VerRegistroActionPerformed

    private void creditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditosActionPerformed
        archivos.setEnabled(false);
        creditos.setEnabled(false);
    }//GEN-LAST:event_creditosActionPerformed

    public void abrirS(){
        respuestaSeguridad = JOptionPane.showConfirmDialog(null,"¿Estas seguro de la selección?",null,
                      JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        while(respuestaSeguridad!=0 && respuestaSeguridad!=1){
                  respuestaSeguridad = JOptionPane.showConfirmDialog(null,"¿Estas seguro de la selección?",null,
                          JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void abrirI(){
        abrirImagenes = GestorImagenes.abrirImagenes();
        if(abrirImagenes==true){
            abrirS();
            if(respuestaSeguridad==0){
                if(rutas.size()>=5){
                    if(rutas.size() <= maxImagenes){
                        pasos = new Pasos(this.principal);
                        this.principal.add(pasos);
                        pasos.setVisible(true);
                    }else{
                        Validacion v = new Validacion(principal);
                        this.principal.add(v);
                        v.setVisible(true);
                    }
                }else{
                    respuestaSeguridad = JOptionPane.showConfirmDialog(null,"Se deben seleccionar un mínimo de 5 imágenes",null,
                      JOptionPane.CLOSED_OPTION,JOptionPane.WARNING_MESSAGE);
                    while(respuestaSeguridad!=0){
                              respuestaSeguridad = JOptionPane.showConfirmDialog(null,"Se deben seleccionar un mínimo de 5 imágenes",null,
                                      JOptionPane.CLOSED_OPTION,JOptionPane.WARNING_MESSAGE);
                    }
                    archivos.setEnabled(true);
                    creditos.setEnabled(true);
                }
              }else if(respuestaSeguridad==1){
                  abrirI();
              }
        }
    }
    
    public void abrirV(){
        abrirVideo = GestorVideo.abrirVideo();
        long vInfo = duracionVideo();
        if(abrirVideo==true){
            abrirS();
            if(respuestaSeguridad==0){
                cargando = new Cargando(this.principal,vInfo);
                this.principal.add(cargando);
                HiloTest.active  = true;
                Video ventanaVideo = new Video(this.principal);
                HiloTest h = new HiloTest(cargando);
                h.cargarVideo(ventanaVideo);
                h.start();
            }else if(respuestaSeguridad==1){
                abrirV();
            }
        }
    }
    
    public long duracionVideo(){
        Encoder encoder = new Encoder();
        MultimediaInfo info;
        long dInfo = 0;
        try {
            info = encoder.getInfo(new File(video));
            dInfo = info.getDuration();
            System.out.println(""+dInfo);
        } catch (EncoderException ex) {
            Logger.getLogger(Video.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dInfo;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
//                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                try {
////                    UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
//                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
//                } catch (Exception e) { }
                new Prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirImagen;
    private javax.swing.JMenuItem AbrirVideo;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem VerRegistro;
    public static javax.swing.JMenu archivos;
    private javax.swing.JMenuBar barra;
    public static javax.swing.JMenu creditos;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    public javax.swing.JDesktopPane principal;
    // End of variables declaration//GEN-END:variables
}
