/*
 */
package GUI_Generales;

import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.Timer;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author rebel
 */
public class Resultados extends javax.swing.JInternalFrame {
    
    public JDesktopPane principal;
    public int s;
    public ArrayList<ImageIcon> imagen;
    public ArrayList<ImageIcon> imagenHistograma;
    public ArrayList<ImageIcon> imagenAux;
    public ArrayList<ImageIcon> imagenPuntos;
    public ArrayList<ImageIcon> imagenPromedio;
    public ArrayList<ImageIcon> imagenEstadistica;
    
    public int contador = 1;
    public Timer timer = null;
    public String rutaProyecto;
    
    private int cantidadHistograma,cantidadPromedio,cantidadPuntoInteres,cantidadEstadistica;
    private int indexHistograma,indexPromedio,indexPuntoInteres;
    private int indexEstadistica;
    
    public ArrayList<String> listaArchivos;
    private String comprimido; 
    private String folderComprimir; // SourceFolder path
    public ImageIcon izquierdaR,derechaR,playR,pauseR,izquierdaG,derechaG;
    /**
     * Creates new form CorrecciónImagenes
     */
    public Resultados() {
        initComponents();
        this.setLocation((this.principal.getWidth()-this.getWidth())/2,(this.principal.getHeight()-this.getHeight())/2);
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    public Resultados(JDesktopPane principal,String ruta) {
        initComponents();
        
        mostrarIconos();
       
       this.principal = principal;
       this.setLocation((this.principal.getWidth()-this.getWidth())/2,(this.principal.getHeight()-this.getHeight())/2);
       ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
       rutaProyecto = ruta;
       indexHistograma = 1;
       indexPromedio = 1;
       indexPuntoInteres = 1;
       indexEstadistica = 1;
       
       cantidadHistograma = 2;
       cantidadPromedio = 2;
       cantidadPuntoInteres = 2;
       cantidadEstadistica = 4;
               
       cargarHistograma(ruta);
       cargarPromedios(ruta);
       cargarPuntos(ruta);
       cargarImagenes(ruta);
       cargarEstadistica(ruta);
       
       imagenAux = imagen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        mostrarImagenes = new javax.swing.JLabel();
        play = new javax.swing.JButton();
        izquierda = new javax.swing.JButton();
        derecha = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        menu = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        muestraPromedio = new javax.swing.JLabel();
        anteriorPromedio = new javax.swing.JButton();
        siguientePromedio = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        muestraPuntos = new javax.swing.JLabel();
        anteriorPuntos = new javax.swing.JButton();
        siguientePuntos = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        muestraHistogramas = new javax.swing.JLabel();
        anteriorHistograma = new javax.swing.JButton();
        siguienteHistograma = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        muestraEstadistica = new javax.swing.JLabel();
        anteriorEstadistica = new javax.swing.JButton();
        siguienteEstadistica = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 4));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Imagenes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 153, 153))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(441, 446));

        mostrarImagenes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        izquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izquierdaActionPerformed(evt);
            }
        });

        derecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derechaActionPerformed(evt);
            }
        });

        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(mostrarImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(pause, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mostrarImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pause, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 153, 153))); // NOI18N

        menu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        menu.setForeground(new java.awt.Color(0, 153, 153));
        menu.setText("Terminar");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Exportar Graficas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 153, 153));
        jButton5.setText("Descargar .zip");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu)
                .addGap(149, 149, 149))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Promedio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 153, 153))); // NOI18N

        muestraPromedio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        muestraPromedio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        muestraPromedio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                muestraPromedioMouseClicked(evt);
            }
        });

        anteriorPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorPromedioActionPerformed(evt);
            }
        });

        siguientePromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguientePromedioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(muestraPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(anteriorPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(siguientePromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(muestraPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anteriorPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siguientePromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Puntos de Interés", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 153, 153))); // NOI18N

        muestraPuntos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        muestraPuntos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        muestraPuntos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                muestraPuntosMouseClicked(evt);
            }
        });

        anteriorPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorPuntosActionPerformed(evt);
            }
        });

        siguientePuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguientePuntosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(muestraPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(anteriorPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(siguientePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(muestraPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anteriorPuntos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siguientePuntos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Histogramas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 153, 153))); // NOI18N

        muestraHistogramas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        muestraHistogramas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        muestraHistogramas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                muestraHistogramasMouseClicked(evt);
            }
        });

        anteriorHistograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorHistogramaActionPerformed(evt);
            }
        });

        siguienteHistograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteHistogramaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(muestraHistogramas, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(anteriorHistograma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(siguienteHistograma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(muestraHistogramas, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anteriorHistograma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siguienteHistograma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estadísticas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 153, 153))); // NOI18N

        muestraEstadistica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        muestraEstadistica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                muestraEstadisticaMouseClicked(evt);
            }
        });

        anteriorEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorEstadisticaActionPerformed(evt);
            }
        });

        siguienteEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteEstadisticaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(muestraEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(anteriorEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(siguienteEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(muestraEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anteriorEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siguienteEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        
        if(timer == null){
            timer = new Timer(600,new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent ae) {

                        mostrarImagenes.setIcon(new ImageIcon(imagenAux.get(contador).getImage().getScaledInstance(340,
                    340,Image.SCALE_DEFAULT)));
                        contador++;
                        if(contador == s){
                            contador = 1;
                        }
                    }
                });
            timer.start();
        }else{
            
            if(timer.isRunning()){
                timer.restart();
            }else{
                timer = new Timer(600,new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent ae) {

                        mostrarImagenes.setIcon(new ImageIcon(imagenAux.get(contador).getImage().getScaledInstance(340,
                    340,Image.SCALE_DEFAULT)));
                        contador++;
                        if(contador == s){
                            contador = 1;
                        }
                    }
                });
                timer.start();
            }
            
        }
        
        
    }//GEN-LAST:event_playActionPerformed

    private void izquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izquierdaActionPerformed
        
        if( timer != null ){
            if(timer.isRunning()){
                timer.stop();
            }

            if(contador == 1){
                contador =s;
            }
            contador--;
            mostrarImagenes.setIcon(new ImageIcon(imagenAux.get(contador).getImage().getScaledInstance(340,
                    340,Image.SCALE_DEFAULT)));
        }
        
//        mostrarImagenes.setIcon(imagen[contador]);
    }//GEN-LAST:event_izquierdaActionPerformed

    private void derechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derechaActionPerformed
        
        if(timer != null){
            if(timer.isRunning()){
                timer.stop();
            }

            if(contador == s-1){
                contador = 0;
            }
            contador++;
            mostrarImagenes.setIcon(new ImageIcon(imagenAux.get(contador).getImage().getScaledInstance(340,
                    340,Image.SCALE_DEFAULT)));
        }
//        mostrarImagenes.setIcon(imagen[contador]);
    }//GEN-LAST:event_derechaActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        if(timer.isRunning()){
            timer.stop();
        }
    }//GEN-LAST:event_pauseActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        dispose();
        GUI_Generales.Principal.archivos.setEnabled(true);
        GUI_Generales.Principal.creditos.setEnabled(true);
    }//GEN-LAST:event_menuActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        listaArchivos = new ArrayList<>();
        
        String rutaUsuario = System.getProperty("user.home");
        String rutaVideoOriginal = rutaUsuario+"\\Documents\\proyecto.zip";
        
        comprimido = rutaVideoOriginal;
        folderComprimir = rutaProyecto;
        
        generarListaArchivos( new File( folderComprimir ) );
        comprimelo( comprimido );
        
        JOptionPane.showMessageDialog(null,"Se mostrara la ubicacion el archivo",
                "Operación realizada correctamente",JOptionPane.INFORMATION_MESSAGE);
        
        Runtime rt = Runtime.getRuntime();
        
        try {
            Process p = rt.exec(new String[]{"explorer.exe",comprimido});
        } catch (IOException ex) {
        
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void muestraHistogramasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_muestraHistogramasMouseClicked
        try {
            
            String[] nombres = {"inicio.png","mitad.png","final.png"};
            String nom = nombres[indexHistograma];
            String url = rutaProyecto+"\\graficas\\"+nom;
            ProcessBuilder p = new ProcessBuilder();
            p.command("cmd.exe","/c",url);
            p.start();
        } catch (IOException ex) {
            Logger.getLogger(Resultados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_muestraHistogramasMouseClicked

    private void anteriorHistogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorHistogramaActionPerformed
        indexHistograma--;
         
        if( indexHistograma >= 0 && indexHistograma <= cantidadHistograma ){
            
            muestraHistogramas.setIcon(new ImageIcon(imagenHistograma.get(indexHistograma).getImage().getScaledInstance(399,
                171,Image.SCALE_DEFAULT)));
            
        }else{
            indexHistograma = 0;
        }
        
       
    }//GEN-LAST:event_anteriorHistogramaActionPerformed

    private void siguienteHistogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteHistogramaActionPerformed
        indexHistograma++;
        
        if( indexHistograma >= 0 && indexHistograma <= cantidadHistograma ){
            
            muestraHistogramas.setIcon(new ImageIcon(imagenHistograma.get(indexHistograma).getImage().getScaledInstance(399,
                171,Image.SCALE_DEFAULT)));
            
        }else{
            indexHistograma = cantidadHistograma;
        }
                
    }//GEN-LAST:event_siguienteHistogramaActionPerformed

    private void anteriorPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorPromedioActionPerformed
        indexPromedio--;
         
        if( indexPromedio >= 0 && indexPromedio <= cantidadPromedio ){
            
            muestraPromedio.setIcon(new ImageIcon(imagenPromedio.get(indexPromedio).getImage().getScaledInstance(399,
                171,Image.SCALE_DEFAULT)));
            
        }else{
            indexPromedio = 0;
        }
    }//GEN-LAST:event_anteriorPromedioActionPerformed

    private void siguientePromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguientePromedioActionPerformed
        indexPromedio++;
        
        if( indexPromedio >= 0 && indexPromedio <= cantidadPromedio ){
            
            muestraPromedio.setIcon(new ImageIcon(imagenPromedio.get(indexPromedio).getImage().getScaledInstance(399,
                171,Image.SCALE_DEFAULT)));
            
        }else{
            indexPromedio = cantidadPromedio;
        }
    }//GEN-LAST:event_siguientePromedioActionPerformed

    private void muestraPromedioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_muestraPromedioMouseClicked
        try {
            String[] nombres = {"Celsius.png","Farenheit.png","Kelvin.png"};
            String nom = nombres[indexPromedio];
            String url = rutaProyecto+"\\graficas\\"+nom;
            ProcessBuilder p = new ProcessBuilder();
            p.command("cmd.exe","/c",url);
            p.start();
        } catch (IOException ex) {
            Logger.getLogger(Resultados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_muestraPromedioMouseClicked

    private void anteriorPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorPuntosActionPerformed
        indexPuntoInteres--;
         
        if( indexPuntoInteres >= 0 && indexPuntoInteres <= cantidadPuntoInteres ){
            
            muestraPuntos.setIcon(new ImageIcon(imagenPuntos.get(indexPuntoInteres).getImage().getScaledInstance(399,
                171,Image.SCALE_DEFAULT)));
            
        }else{
            indexPuntoInteres = 0;
        }
    }//GEN-LAST:event_anteriorPuntosActionPerformed

    private void siguientePuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguientePuntosActionPerformed
        indexPuntoInteres++;
        
        if( indexPuntoInteres >= 0 && indexPuntoInteres <= cantidadPuntoInteres ){
            
            muestraPuntos.setIcon(new ImageIcon(imagenPuntos.get(indexPuntoInteres).getImage().getScaledInstance(399,
                171,Image.SCALE_DEFAULT)));
            
        }else{
            indexPuntoInteres = cantidadPuntoInteres;
        }
    }//GEN-LAST:event_siguientePuntosActionPerformed

    private void muestraPuntosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_muestraPuntosMouseClicked
        try {
            String[] nombres = {"Punto Interes Celsius.png","Punto Interes Farenheit.png","Punto Interes Kelvin.png"};
            String nom = nombres[indexPuntoInteres];
            String url = rutaProyecto+"\\graficas\\"+nom;
            ProcessBuilder p = new ProcessBuilder();
            p.command("cmd.exe","/c",url);
            p.start();
        } catch (IOException ex) {
            Logger.getLogger(Resultados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_muestraPuntosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Image iPuntos = imagenPuntos.get(indexPuntoInteres).getImage();
        Image iPromedio = imagenPromedio.get(indexPromedio).getImage();
        Image iHistograma = imagenHistograma.get(indexHistograma).getImage();
        Image iEstadistica = imagenEstadistica.get(indexEstadistica).getImage();
        
        JOptionPane.showMessageDialog(null,"Se guardaran las gráficas que se muestran en pantalla",
                    "Guardar imagen",JOptionPane.INFORMATION_MESSAGE);
        
        JOptionPane.showMessageDialog(null,"Guardar grafica de puntos de interés",
                    "Guardar imagen",JOptionPane.INFORMATION_MESSAGE);
        
        guardarImagen(iPuntos, "Puntos.png");
        
        JOptionPane.showMessageDialog(null,"Guardar gráfica de promedios",
                    "Guardar imagen",JOptionPane.INFORMATION_MESSAGE);
        
        guardarImagen(iPromedio, "Promedio.png");
        
        JOptionPane.showMessageDialog(null,"Guardar gráfica de Histograma",
                    "Guardar imagen",JOptionPane.INFORMATION_MESSAGE);
        
        guardarImagen(iHistograma, "Histograma.png");
        
        JOptionPane.showMessageDialog(null,"Guardar gráfica de Estadistica",
                    "Guardar imagen",JOptionPane.INFORMATION_MESSAGE);
        
        guardarImagen(iEstadistica, "Estadistica.png");
        
        JOptionPane.showMessageDialog(null,"Se a guardado correctamente las imágenes",
                    "Exito",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void siguienteEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteEstadisticaActionPerformed
        indexEstadistica++;
        
        if( indexEstadistica >= 0 && indexEstadistica <= cantidadEstadistica ){
            
            muestraEstadistica.setIcon(new ImageIcon(imagenEstadistica.get(indexEstadistica).getImage().getScaledInstance(399,
                171,Image.SCALE_DEFAULT)));
            
        }else{
            indexEstadistica = cantidadEstadistica;
        }
    }//GEN-LAST:event_siguienteEstadisticaActionPerformed

    private void anteriorEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorEstadisticaActionPerformed
        indexEstadistica--;
         
        if( indexEstadistica >= 0 && indexEstadistica <= cantidadEstadistica ){
            
            muestraEstadistica.setIcon(new ImageIcon(imagenEstadistica.get(indexEstadistica).getImage().getScaledInstance(399,
                171,Image.SCALE_DEFAULT)));
            
        }else{
            indexEstadistica = 0;
        }
    }//GEN-LAST:event_anteriorEstadisticaActionPerformed

    private void muestraEstadisticaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_muestraEstadisticaMouseClicked
        try {
            String[] nombres = {"Mediana.png","Media.png","Moda.png","Varianza.png","Desviacion estandar.png"};
            String nom = nombres[indexEstadistica];
            String url = rutaProyecto+"\\graficas\\"+nom;
            ProcessBuilder p = new ProcessBuilder();
            p.command("cmd.exe","/c",url);
            p.start();
        } catch (IOException ex) {
            Logger.getLogger(Resultados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_muestraEstadisticaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anteriorEstadistica;
    private javax.swing.JButton anteriorHistograma;
    private javax.swing.JButton anteriorPromedio;
    private javax.swing.JButton anteriorPuntos;
    private javax.swing.JButton derecha;
    private javax.swing.JButton izquierda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton menu;
    private javax.swing.JLabel mostrarImagenes;
    private javax.swing.JLabel muestraEstadistica;
    private javax.swing.JLabel muestraHistogramas;
    private javax.swing.JLabel muestraPromedio;
    private javax.swing.JLabel muestraPuntos;
    private javax.swing.JButton pause;
    private javax.swing.JButton play;
    private javax.swing.JButton siguienteEstadistica;
    private javax.swing.JButton siguienteHistograma;
    private javax.swing.JButton siguientePromedio;
    private javax.swing.JButton siguientePuntos;
    // End of variables declaration//GEN-END:variables
    
    private void cargarEstadistica(String ruta) {
        
        String[] nombres = {"Mediana.png","Media.png","Moda.png","Varianza.png","Desviacion estandar.png"};
        
        imagenEstadistica = new ArrayList<>();
        
        for(int i=0; i<nombres.length; i++){
            
            File f = new File(ruta+"\\graficas\\"+nombres[i]);
            imagenEstadistica.add(new ImageIcon(f.getAbsolutePath())) ;
            
        }
        
        muestraEstadistica.setIcon(new ImageIcon(imagenEstadistica.get(indexEstadistica).getImage().getScaledInstance(399,
                171,Image.SCALE_DEFAULT)));
        
    }
    
    private void cargarImagenes(String ruta) {
       
        
        File f = new File(ruta+"\\Imagenes");
        File[] imagenes = f.listFiles();
        
        s = imagenes.length;
        imagen = new ArrayList<>();
        
        for(int i=0; i<s; i++){
            
            imagen.add(new ImageIcon(imagenes[i].getAbsolutePath()));
            
        }
        
        mostrarImagenes.setIcon(new ImageIcon(imagen.get(1).getImage().getScaledInstance(340,
                340,Image.SCALE_DEFAULT)));
        
    }

    private void cargarHistograma(String ruta) {
        
        String[] nombres = {"inicio.png","mitad.png","final.png"};
        
        imagenHistograma = new ArrayList<>();
        
        for(int i=0; i<nombres.length; i++){
            
            File f = new File(ruta+"\\graficas\\"+nombres[i]);
            imagenHistograma.add(new ImageIcon(f.getAbsolutePath())) ;
            
        }
        
        muestraHistogramas.setIcon(new ImageIcon(imagenHistograma.get(indexHistograma).getImage().getScaledInstance(399,
                171,Image.SCALE_DEFAULT)));
    }

    private void cargarPromedios(String ruta) {
        
        String[] nombres = {"Celsius.png","Farenheit.png","Kelvin.png"};
        
        imagenPromedio = new ArrayList<>();
        
        for(int i=0; i<nombres.length; i++){
            
            File f = new File(ruta+"\\graficas\\"+nombres[i]);
            imagenPromedio.add(new ImageIcon(f.getAbsolutePath()));
            
        }
        muestraPromedio.setIcon(new ImageIcon(imagenPromedio.get(indexPromedio).getImage().getScaledInstance(399,
                171,Image.SCALE_DEFAULT)));
    }

    private void cargarPuntos(String ruta) {
        String[] nombres = {"Punto Interes Celsius.png","Punto Interes Farenheit.png","Punto Interes Kelvin.png"};
        
        imagenPuntos = new ArrayList<>();
        
        for(int i=0; i<nombres.length; i++){
            
            File f = new File(ruta+"\\graficas\\"+nombres[i]);
            imagenPuntos.add(new ImageIcon(f.getAbsolutePath()));
            
        }
        
        muestraPuntos.setIcon(new ImageIcon(imagenPuntos.get(indexPuntoInteres).getImage().getScaledInstance(399,
                171,Image.SCALE_DEFAULT)));
    }
    
    public void comprimelo(String archivoZip){
        
        byte[] buffer = new byte[1024];
        String source = new File(folderComprimir).getName();
        
        try{
            
            FileOutputStream fos = new FileOutputStream(archivoZip); 
            ZipOutputStream zos = new ZipOutputStream(fos); 

            System.out.println("Destino del Zip : " + archivoZip);

            FileInputStream in = null;

            for ( String file: listaArchivos ) {

                System.out.println("Archivo agregado : " + file); 
                ZipEntry ze = new ZipEntry(source + File.separator + file); 
                zos.putNextEntry(ze); 

                try { 

                    in = new FileInputStream(folderComprimir + File.separator + file); 
                    int len; 

                    while ((len = in .read(buffer)) > 0) {

                        zos.write(buffer, 0, len); 

                    } 
                } finally { 

                    in.close();

                } 

            }
            
            zos.closeEntry(); 
            System.out.println("Zip creado satisfactoriamente");
            zos.close();
            
            
        }catch(IOException ex){
            
        }
        
    }
    
    public void generarListaArchivos(File f){
        
        if( f.isFile() ){
            
            listaArchivos.add(generarZip(f.toString())); 
            
        }
        
        if( f.isDirectory() ){
            
            String[] subDirectorio = f.list(); 
            
            for (String nombreArchivo: subDirectorio) { 
                
                generarListaArchivos(new File(f, nombreArchivo));
             
            } 
            
        }
    }
    
    private String generarZip(String archivo) { 
        
        String arc = archivo.substring(folderComprimir.length() + 1 , archivo.length() );
        
        return arc;
        
    }
    
    
    public void guardarImagen(Image img,String nombre)
    {
        try {
            
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Imagenes", "jpg","png");
            // convertimos a buffered

            BufferedImage bi = toBufferedImage(img);
            // declaramos la ventana para seleccionar la ruta
            JFileChooser ventana = new JFileChooser();
            ventana.setAcceptAllFileFilterUsed(false);
            ventana.addChoosableFileFilter(filter);
            ventana.setSelectedFile( new File(""+nombre) );
            
            int res = ventana.showSaveDialog(null);
            
            if (res == JFileChooser.APPROVE_OPTION){
                File archivo = ventana.getSelectedFile();
                
                if( !archivo.getName().endsWith(".png") ){
                    
                    String ruta = archivo.getAbsolutePath()+".png";
                    File aux = new File(ruta);
                    ImageIO.write(bi,"png", aux);
                    
                }else{
                    
                    ImageIO.write(bi,"png", archivo);
                    
                }

            }
            
        } catch (IOException ex) {
            
        }
          
    }
    
    private BufferedImage toBufferedImage (Image imagen){
         // imagen es un objeto de tipo BufferedImage
        if (imagen instanceof BufferedImage){
          return (BufferedImage)imagen;
        }
        BufferedImage bi = 
        new BufferedImage(imagen.getWidth(null), imagen.getHeight(null), BufferedImage.TYPE_INT_RGB);
        
        Graphics2D nueva = bi.createGraphics();
        nueva.drawImage(imagen, 0, 0,null);
        nueva.dispose();
        
        return bi;
    }
    
    public void mostrarIconos(){
        izquierdaR = new ImageIcon("src\\Fotos\\atras.png");
        derechaR = new ImageIcon("src\\Fotos\\adelante.png");
        playR = new ImageIcon("src\\Fotos\\play.png");
        pauseR = new ImageIcon("src\\Fotos\\pausa.png");
        izquierdaG = new ImageIcon("src\\Fotos\\flechaIzquierda.png");
        derechaG = new ImageIcon("src\\Fotos\\flechaDerecha.png");
        
        izquierdaR.setImage(izquierdaR.getImage().getScaledInstance(30,30,Image.SCALE_DEFAULT));
        derechaR.setImage(derechaR.getImage().getScaledInstance(30,30,Image.SCALE_DEFAULT));
        playR.setImage(playR.getImage().getScaledInstance(30,30,Image.SCALE_DEFAULT));
        pauseR.setImage(pauseR.getImage().getScaledInstance(30,30,Image.SCALE_DEFAULT));
        izquierdaG.setImage(izquierdaG.getImage().getScaledInstance(30,30,Image.SCALE_DEFAULT));
        derechaG.setImage(derechaG.getImage().getScaledInstance(30,30,Image.SCALE_DEFAULT));
        
        izquierda.setIcon(izquierdaR);
        derecha.setIcon(derechaR);
        play.setIcon(playR);
        pause.setIcon(pauseR);
        anteriorPromedio.setIcon(izquierdaG);
        anteriorPuntos.setIcon(izquierdaG);
        anteriorHistograma.setIcon(izquierdaG);
        anteriorEstadistica.setIcon(izquierdaG);
        siguientePromedio.setIcon(derechaG);
        siguientePuntos.setIcon(derechaG);
        siguienteHistograma.setIcon(derechaG);
        siguienteEstadistica.setIcon(derechaG);
        
        izquierda.setContentAreaFilled(false);
        derecha.setContentAreaFilled(false);
        play.setContentAreaFilled(false);
        pause.setContentAreaFilled(false);
        anteriorPromedio.setContentAreaFilled(false);
        anteriorPuntos.setContentAreaFilled(false);
        anteriorHistograma.setContentAreaFilled(false);
        anteriorEstadistica.setContentAreaFilled(false);
        siguientePromedio.setContentAreaFilled(false);
        siguientePuntos.setContentAreaFilled(false);
        siguienteHistograma.setContentAreaFilled(false);
        siguienteEstadistica.setContentAreaFilled(false);
    }

    
}
